name: Deploy to ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

    - name: Build, tag, and push Docker image
      run: |
        IMAGE_TAG=latest
        docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
        docker tag flask-app:latest 637423320338.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
        docker push 637423320338.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
      working-directory: app

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: Update ECS Service with new image
      run: |
        IMAGE_TAG=latest
        aws ecs update-service --cluster flask-app-cluster --service flask-app-service --force-new-deployment --task-definition $(aws ecs describe-task-definition --task-definition flask-app-task --query "taskDefinition.taskDefinitionArn" --output text) --container-definitions $(jq -c '.[] | if .name == "flask-app" then .image = "'${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG'" else . end' <(aws ecs describe-task-definition --task-definition flask-app-task --query "taskDefinition.containerDefinitions" --output json))
      working-directory: terraform