name: Deploy to ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      working-directory: app

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: Update ECS Service with new image
      run: |
        IMAGE_TAG=${{ github.sha }}
        TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition flask-app-task --query "taskDefinition.{family:family,networkMode:networkMode,containerDefinitions:containerDefinitions,cpu:cpu,memory:memory,executionRoleArn:executionRoleArn,taskRoleArn:taskRoleArn,requiresCompatibilities:requiresCompatibilities}" --output json)
        
        echo $TASK_DEFINITION | jq --arg IMAGE_TAG "$IMAGE_TAG" '.containerDefinitions[0].image = "'${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG'"' > new-task-def.json
        
        aws ecs register-task-definition --cli-input-json file://new-task-def.json
        
        aws ecs update-service --cluster flask-app-cluster --service flask-app-service --force-new-deployment
      working-directory: terraform