name: Deploy to ECS Fargate
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: app
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: '${{ secrets.AWS_REGION }}'
      - name: Terraform Init
        run: terraform init
        working-directory: terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: terraform
      - name: Install ECS CLI
        run: curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
             chmod +x /usr/local/bin/ecs-cli
      - name: ECS Deploy
        run: >
          ecs-cli configure --cluster flask-app-cluster --default-launch-type
          FARGATE --config-name flask-config --region ${{ secrets.AWS_REGION }}
        working-directory: terraform
